stages:
  - "build"
  - "deploy"

.variables: &variables
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2"

.variables_develop: &variables_develop
  <<: *variables
  NODE_PROJECT_VERSION_SUFFIX: "-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-SNAPSHOT"

.variables_release: &variables_release
  <<: *variables
  NODE_PROJECT_VERSION_SUFFIX: ""

.artifacts: &artifacts
  expire_in: "15 mins"
  paths:
    - "./dist/"

.cache: &cache
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - "./.m2/"
    - "./node_modules/"

.regex:
  # Semantic Versioning 2.0.0 regex (from: https://github.com/npm/node-semver/).
  - &regex_version "/^v?(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][a-zA-Z0-9-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][a-zA-Z0-9-]*))*))?(?:\\+([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?$/"

build:develop:
  stage: "build"
  variables:
    <<: *variables_develop
  script:
    - "npm install"
    - "npm run lint"
    - "npm run build:dev"
  artifacts:
    <<: *artifacts
  cache:
    <<: *cache
  except:
    - *regex_version

build:release:
  stage: "build"
  variables:
    <<: *variables_release
  script:
    - "npm install"
    - "npm run lint"
    - "npm run build:prod"
  artifacts:
    <<: *artifacts
  cache:
    <<: *cache
  only:
    - *regex_version

deploy:develop:mvn:
  stage: "deploy"
  dependencies:
    - "build:develop"
  variables:
    <<: *variables_develop
  script:
    - "npm install"
    - "npm run deploy:dev"
  cache:
    <<: *cache
  except:
    - *regex_version

deploy:release:mvn:
  stage: "deploy"
  dependencies:
    - "build:release"
  variables:
    <<: *variables_release
  script:
    - "npm install"
    - "npm run deploy:prod"
  cache:
    <<: *cache
  only:
    - *regex_version

.deploy:develop:testing:template:
  stage: "deploy"
  dependencies:
    - "build:develop"
  script:
    - "mv ./dist/stsearch.zip ./20_stsearch-autodeploy.zip"
    - |
      lftp <<-EOF
        set sftp:connect-program 'ssh -oStrictHostKeyChecking=no';
        open 'sftp://${LINCEBI_TESTING_SFTP_USER:?}:${LINCEBI_TESTING_SFTP_PASSWORD:?}@${LINCEBI_TESTING_SFTP_HOST:?}:${LINCEBI_TESTING_SFTP_PORT:?}';
        put -O './data/${LINCEBI_TESTING_ENV:?}/init.d/' ./20_stsearch-autodeploy.zip;
        bye;
      EOF
  except:
    - *regex_version

deploy:develop:testing:a:manual:
  extends: ".deploy:develop:testing:template"
  when: "manual"
  variables:
    LINCEBI_TESTING_ENV: "a"
  only: ["master"]

deploy:develop:testing:b:manual:
  extends: ".deploy:develop:testing:template"
  when: "manual"
  variables:
    LINCEBI_TESTING_ENV: "b"
  only: ["master", "/^[0-9]+-.+$/"]

deploy:develop:testing:*:scheduled:
  extends: ".deploy:develop:testing:template"
  only: ["schedules"]
