stages:
  - "build"
  - "deploy"

.variables: &variables
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2"

.variables_develop: &variables_develop
  <<: *variables

.variables_release: &variables_release
  <<: *variables

.artifacts: &artifacts
  expire_in: "15 mins"
  paths:
    - "./dist/"

.cache: &cache
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - "./.m2/"
    - "./node_modules/"

.regex:
  # Semantic Versioning 2.0.0 regex (from: https://github.com/npm/node-semver/).
  - &regex_version "/^v?(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][a-zA-Z0-9-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][a-zA-Z0-9-]*))*))?(?:\\+([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?$/"

build:develop:
  stage: "build"
  variables:
    <<: *variables_develop
  script:
    - "npm install"
    - "npm run lint"
    - "npm run build:dev"
  artifacts:
    <<: *artifacts
  cache:
    <<: *cache
  except:
    - *regex_version

build:release:
  stage: "build"
  variables:
    <<: *variables_release
  script:
    - "npm install"
    - "npm run lint"
    - "npm run build:prod"
  artifacts:
    <<: *artifacts
  cache:
    <<: *cache
  only:
    - *regex_version

deploy:develop:mvn:
  stage: "deploy"
  dependencies:
    - "build:develop"
  variables:
    <<: *variables_develop
  script:
    - "npm install"
    - "npm run deploy:dev"
  cache:
    <<: *cache
  except:
    - *regex_version

deploy:release:mvn:
  stage: "deploy"
  dependencies:
    - "build:release"
  variables:
    <<: *variables_release
  script:
    - "npm install"
    - "npm run deploy:prod"
  cache:
    <<: *cache
  only:
    - *regex_version
