stages:
  - lint
  - build
  - deploy

before_script:
  - npm install

cache:
  paths:
    - node_modules/

lint:
  stage: lint
  script:
    - npm run lint

build:develop:
  stage: build
  script:
    - npm run build:dev
  artifacts:
    expire_in: 1 hour
    paths:
      - dist/

build:production:
  stage: build
  script:
    - npm run build:prod
  artifacts:
    expire_in: 1 hour
    paths:
      - dist/
  only:
    - /^v([0-9]+\.)+[0-9]$/

deploy:develop:
  stage: deploy
  script:
    - npm run deploy:dev

deploy:production:
  stage: deploy
  script:
    - npm run deploy:prod
  only:
    - /^v([0-9]+\.)+[0-9]$/
